apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-kenchlightyear-com-p
  namespace: jx
spec:
  secretName: tls-kenchlightyear-com-p
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: '*.kenchlightyear.com'
  dnsNames:
  - kenchlightyear.com
  - '*.kenchlightyear.com'
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - kenchlightyear.com
      - '*.kenchlightyear.com'
